### ISSUE TITLE
No need to process non-jar artifacts

### ISSUE THREAD

**Issue by paulk-asert** [io7m-graveyard/modulechaser#4]
When a standalone pom artifact is encountered, the transitive dependencies are correctly followed but there is no need to try to open it as a jar file and look for any interesting contents. The status is currently marked as Unavailable which is possibly okay. Perhaps just saying pom is good enough. I'm not sure there is anything interesting to say from a Java 9 perspective about standalone poms.
```
<?xml version="1.0" encoding="UTF-8"?>
<project
  xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>
  <!-- dummy entries -->
  <groupId>junit</groupId>
  <artifactId>junit</artifactId>
  <version>4.12</version>

  <dependencies>
    <dependency>
      <groupId>org.jboss.spec</groupId>
      <artifactId>jboss-javaee-7.0</artifactId>
      <version>1.1.1.Final</version>
      <type>pom</type>
    </dependency>
  </dependencies>

</project>
```
Error will be something like:
```
...
[INFO] artifact org.jboss.spec:jboss-javaee-7.0: checking for updates from central
[ERROR] error resolving:
java.util.zip.ZipException: zip END header not found
    at java.util.zip.ZipFile$Source.zerror ...
```

**Comment by io7m** [comment]
Yep, I'll be working on this shortly.

**Comment by io7m** [comment]
Non-Jar type projects now show up as a grey "Not a jar" field. The code essentially tries to open the file as a jar and if it fails for any reason, it assumes it isn't a jar. This should, as a result, automatically work for the more unusual packaging types such as `bundle`, `war`, `ear`, `maven-plugin`, etc.
